out = "out"
posts = "posts"
title = "Zink Blog"
facicon = "favicon.ico"
image = "https://avatars.githubusercontent.com/u/138247979?s=400&u=f5c906945b7378f8063d845c7181e7a3f0e25070&v=4"
site = "zinkonx"
