name: sonata

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: clearloop/sonata@0.1.7

      - name: Build the site
        run: sonata build

      - name: Copy pull action
        run: |
          mkdir -p ./out/.github/
          cp .github/pull.yaml ./out/.github/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          exclude_assets: ""
